### ISSUE TITLE
Ultrawide support and increase height.

### ISSUE THREAD

**Issue by CallMeJay360** [pixelRena/games-recommendations#3]
- It doesn't seem to scale well on Ultrawide (3440x1440).

- Increasing the height to show more games would improve the visibility and navigation of the site.

![image](https://user-images.githubusercontent.com/127843722/230263495-caa5d72c-3b08-4f64-b476-3c2dc5db940a.png)

**Comment by pixelRena** [comment]
Thanks! I will be updating this to support ultrawide a lot better soon in the next updates.

**Comment by pixelRena** [comment]
## Ultrawide Support Added
Updates to styling can be found here for more information: https://github.com/pixelRena/Play-This-Next/commit/2309ea2b0159798de9fe535cf65636eba5a1810e

Code has been tested on 3440x1440 included. 
If any unexpected bugs occur, make another issue.
